### ISSUE TITLE
Add meta data section

### ISSUE THREAD

**Issue by CramBL** [CramBL/mtgo-collection-manager#77]
There's an info section with collection info, a similar one could be made but with meta data such as:

- [ ] Goatbots prices last updated
- [ ] Scryfall prices last updated
- [ ] Next set release date
- [ ] (dek-file added moved from collection info to this meta-data section
- [ ] Next available update?

**Comment by CramBL** [comment]
#78 Adds Goatbots, Scryfall prices last updated, and moves dek-file added to a meta-data section
